### ISSUE TITLE
Automatic detection of samconfig.toml

### ISSUE THREAD

**Issue by nmoutschen** [mhlabs/cfn-resource-actions#1]
If there is a `samconfig.toml` file alongside the template file, it would be nice to autodetect it and retrieve the stack name and region from it.

**Comment by ljacobsson** [comment]
Good point! 

Support for extracting the stack name from the samconfig.toml was introduced in the latest release, but it assumes it's located in the project root.

**Comment by nmoutschen** [comment]
Aaah OK! I'm currently testing with [this project](https://github.com/aws-samples/aws-step-functions-twitch-series) which has lots of SAM templates, but none of them is at the root of the project.

**Comment by ljacobsson** [comment]
You have a very good point in that this should support multiple templates. I've been needing it to do the same. v0.0.31 will support this, so please test it out :-)
